<?php
/*  German translation  */
$data = [
    'param_title' => 'Einstellungen',
    'e_mail' => 'E-Mail',
    'reg_title' => 'Benutzer/innen',
    'reg_settings' => 'Anmeldung',
    'reg_users' => 'Liste',
    'reg_captcha' => 'CAАPTCHA',
    'main_page' => 'Startseite',
    'reg_profile' => 'Profil',
    'reg_user_management' => 'Steuerung',
    'hidden' => 'Ausgeblendet',
    'block_position' => 'Position des Blocks mit Tasten auf der Seite',
    'up' => 'Oben',
    'left' => 'Links',
    'on_right' => 'Rechts',
    'fields_for_registration' => 'Liste der Felder für Anmeldung',
    'phone' => 'Telefon',
    'login' => 'Login',
    'password' => 'Passwort',
    'name' => 'Vorname',
    'surname' => 'Name',
    'promo_code' => 'Promo-Code',
    'show_in_profile' => 'Im Profil anzeigen',
    'user_reg_params' => 'Persönliche Felder',
    'apply_changes' => 'Änderungen anwenden',
    'required_fields' => 'Pflichtfelder für Anmeldung',
    'captcha_on' => 'CAPTCHA ein',
    'standard_captcha_on' => 'CAPTCHA ein',
    'feedback_on' => 'CAPTCHA ein',
    'header_code' => 'Kode für Hinzufügen des „header“ einzelner Anmeldungsseiten',
    'captcha' => 'CAPTCHA',
    'page' => 'Seite',
    'address' => 'Adresse',
    'reg_table_name' => 'Name der Tabelle mit Benutzernamen',
    'subscription' => 'Newsletter-Bestellung',
    'terms_of_use' => 'Nutzungsvereinbarung',
    'link_to_user_agreement' => 'Link auf Nutzungsvereinbarung',
    'privacy_policy' => 'Datenschutzrichtlinien',
    'link_to_privacy policy' => 'Link auf Datenschutzrichtlinien',
    'font_base' => 'Namen der Schriftarten für Anmeldungsleiste',
    'design' => 'Design',
    'select_lang' => 'Sprache auswählen (wenn unbestimmt)',
    'fields_for_type' => 'Benutzertyp auswählen',
    'reg_type' => 'Typ auswählen',
    'user' => 'Benutzer/in',
    'add' => 'Hinzufügen',
    'delete' => 'Löschen',
    'none' => 'Aus',
    'search' => 'Suchen',
    'regards_block' => 'Text unter dem Brief',
    'password_send_title' => 'Passwort-Wiederherstellung',
    'password_send_message' => 'Die E-Mail für Passwort-Wiederherstellung wurde an <span class="hlogin-f-nowrap">E-mail</span> gesendet',
    'user_register_title' => 'Erfolgreich angemeldet!',
    'user_register_message' => 'Die E-Mail mit Anmeldungsangaben wurde an <span class="hlogin-f-nowrap">E-mail</span> gesendet.',
    'empty_database' => 'Die erforderliche Tabelle ist in der Datenbank nicht gefunden.',
    'undefined_email' => 'Keine Anmeldungsversuche mit dieser E-Mail',
    'registered_email' => 'Die Anmeldung mit diesem <span class="hlogin-f-nowrap">E-mail</span> wurde schon versucht.<br>Versuchen Sie, die Anmeldedaten wiederherzustellen.',
    'total_error' => 'Laufzeitfehler',
    'again_message' => 'Die Anforderung ist nicht erfüllt. Bitte versuchen Sie später.',
    'pair_mismatch' => 'Nichtübereinstimmung von der E-Mail und dem Passwort',
    'register_on' => 'Anmeldung auf der Seite',
    'change_email_on' => 'E-Mail ändern',
    'recovery_from' => 'Anforderung für Wiederherstellung ',
    'deleted_user' => 'Benutzer/in mit solcher E-Mail wurde gelöscht oder gesperrt',
    'duplicate_pass' => 'Dieses Passwort wurde früher verwendet',
    'link expired' => 'Link abgelaufen',
    'nothing_changed' => 'Keine Änderungen verwendet',
    'user_not_reg' => 'Benutzer/in ist nicht angemeldet',
    'email_not_verified' => 'Aktuelle E-Mail ist nicht bestätigt, <br> hat dem daran gesendeten Link zu folgen',
    'wrong_password' => 'Passwort falsch',
    'enter_page' => 'Eintritt',
    'register_page' => 'Anmeldung',
    'profile_page' => 'Profil',
    'captcha_error' => 'Zeichen vom Bild sind unrichtig angegeben',
    'new_password_page' => 'Passwort ändern',
    'user_new_email' => 'Daten sind geändert',
    'user_new_email_text' => 'E-Mail mit Bestätigung ist an neue <span class="hlogin-f-nowrap">E-mail</span> gesendet',
    'reload_page_or_other_action' => 'Fehlgeschlagen. <br> Bitte aktualisieren die Seite und wiederholen die Anforderung. Sie können auch dem an E-Mail gesendeten Link folgen.',
    'data_validation_failed' => 'Eingegebene Daten haben die Prüfung nicht bestanden',
    'get_url_after_reg' => 'Bitte wechseln zu dieser relativer URL nach der Anmeldung',
    'email_not_confirm' => 'Aktuelle E-Mail ist nicht bestätigt',
    'failed_to_create_user' => 'Benutzer/in konnte nicht erstellt werden',
    'email_confirm_title' => 'Anmeldung von Neubenutzer/in',
    'email_confirm_header' => 'E-Mail-Bestätigung',
    'contact_message' => 'Nachricht senden',
    'save_post_to_log' => 'E-Maile in Log speichern',
    'not_send_by_email' => 'Nicht per E-Mail versenden',
    'save_changes' => 'Änderungen speichern',
    'feedback' => 'Feedback',
    'all' => 'Insgesamt',
    'message_log_success' => 'Daten sind erfolgreich gespeichert!',
    'message_log_error' => 'Datenspeicherungsfehler',
    'email_confirm_message' => [
        'universal' => '<div style="background-color: #ffffff; padding: 6px"><font color="#000000">Um E-Mail-Adresse zu bestätigen, hat man diesem  <a href="{{confirm_link}}" alt="link"><font color="#3399FF">Link</font></a> zu folgen.</font><br><br><br>' . "\n" . 'Wenn der Link nicht funktioniert, fügen Sie den Text in die Adressleiste Ihres Browsers ein:' . "\n" . '<br> <div style="word-wrap:break-word;color:#a9a9a9;max-width:100%">{{confirm_link}}</div><br>{{user_password}}<br>' . "\n" . '{{warning}}</div>'. '<br><br>',
        'base' => '<font color="#000000">Um E-Mail-Adresse zu bestätigen, hat man diesem  <a href="{{confirm_link}}" alt="link"><font color="#330099">Link</font></a> zu folgen.</font><br><br><br>' . "\n" . 'Wenn der Link nicht funktioniert, fügen Sie den Text in die Adressleiste Ihres Browsers ein:' . "\n" . '<br> <div style="word-wrap:break-word;color:#a9a9a9;max-width:100%">{{confirm_link}}</div><br>{{user_password}}<br>' . "\n" . '{{warning}}'. '<br><br>',
        'dark' => '<font color="#ffffff">Um E-Mail-Adresse zu bestätigen, hat man diesem  <a href="{{confirm_link}}" alt="link"><font color="#3399FF">Link</font></a> zu folgen.</font><br><br>' . "\n" . 'Wenn der Link nicht funktioniert, fügen Sie den Text in die Adressleiste Ihres Browsers ein:' . "\n" . '<br> <div style="word-wrap:break-word;color:#a1a1a1;max-width:100%">{{confirm_link}}</div><br>{{user_password}}<br>' . "\n" . '{{warning}}'. '<br><br>',
    ],
    'password_recovery_header' => 'Passwortänderung',
    'password_recovery_message' => [
        'universal' => '<div style="background-color: #ffffff; padding: 6px"><font color="#000000">Für Passwortänderung hat man diesem <a href="{{confirm_link}}" alt="link"><font color="#3399FF">Link</font></a> zu folgen.</font><br><br><br>' . "\n" . 'Wenn der Link nicht funktioniert, fügen Sie den Text in die Adressleiste Ihres Browsers ein:' . "\n" . '<br> <div style="word-wrap:break-word;color:#a9a9a9;max-width:100%">{{recovery_link}}</div><br>{{user_password}}<br>' . "\n" . '{{warning}}</div>'. '<br><br>',
        'base' => '<font color="#000000">Für Passwortänderung hat man diesem <a href="{{confirm_link}}" alt="link"><font color="#330099">Link</font></a> zu folgen.</font><br><br><br>' . "\n" . 'Wenn der Link nicht funktioniert, fügen Sie den Text in die Adressleiste Ihres Browsers ein:' . "\n" . '<br> <div style="word-wrap:break-word;color:#a9a9a9;max-width:100%">{{recovery_link}}</div><br>{{user_password}}<br>' . "\n" . '{{warning}}'. '<br><br>',
        'dark' => '<font color="#ffffff">Für Passwortänderung hat man diesem <a href="{{confirm_link}}" alt="link"><font color="#3399FF">Link</font></a> zu folgen.</font><br><br>' . "\n" . 'Wenn der Link nicht funktioniert, fügen Sie den Text in die Adressleiste Ihres Browsers ein:' . "\n" . '<br> <div style="word-wrap:break-word;color:#a1a1a1;max-width:100%">{{recovery_link}}</div><br>{{user_password}}<br>' . "\n" . '{{warning}}'. '<br><br>',
    ],
    'warning_below' => 'Wenn der Anmeldungsvorgang ist nicht von Ihnen gestartet, ignorieren Sie bitte diese Nachricht. <br> Um Ihr Konto zu schützen, leiten Sie diese E-Mail nicht weiter.',
    'duplicate-english' => 'Doppelten Text in Englisch hinzufügen',
    'add_filter' => 'Filter anwenden',
    'waiting' => 'Bitte warten…',
    'feeedback_message' => [
        'universal' => '<font color="#2c363a"><pre style="background-color: #f4f4f4; color: #2c363a; border: 1px solid #d4dbde; padding:4px; margin-right: 5px;">{{message}}</pre></font>',
        'base' => '<font color="#2c363a"><pre style="color: #2c363a;background-color: #ffffff; padding:4px; margin-right: 5px;">{{message}}</pre></font>',
        'dark' => '<font color="#eeeeee"><pre style="color: #eeeeee; padding:4px; margin-right: 5px;">{{message}}</pre></font>',
    ]
];
return $data;