if (typeof mHLogin.i18n === 'undefined') {
    mHLogin.i18n = {
        languages: uHLogin.languages,
        get: function (tag) {
            return typeof this.data.ru[tag] !== 'undefined' ? this.data.ru[tag] : tag;
        },
        data: {
            ru: {
                data_send: 'Данные отправлены',
                data_not_send: 'Данные НЕ отправлены',
                password: 'Пароль',
                input_password: '&ge;6 цифр и латинских символов',
                password_repeat: 'Повтор пароля',
                submit: 'Отправить',
                sign_in: 'Вход',
                enter: 'Вход',
                registration_title: 'Регистрация',
                phone: 'Номер телефона',
                name: 'Имя',
                surname: 'Фамилия',
                address: 'Адрес',
                promocode: 'Промокод',
                familar: 'Ознакомлен с',
                terms: 'Правилами использования',
                conditions: 'все условия принимаю',
                privacy_policy: 'Политикой конфиденциальности',
                generate_password: 'Сгенерировать пароль',
                and: 'и',
                on_email: 'На E-mail',
                send_password: 'Восстановление пароля',
                forgot_password: 'Забыли пароль?',
                show_password: 'Показать пароль',
                hide_password: 'Скрыть пароль',
                remember_login: 'Запомнить вход',
                close: 'Закрыть',
                mess_password: 'Пароль будет выслан на E-mail',
                new_password: 'Новый пароль',
                old_password: 'Текущий пароль',
                u_error: 'Возникла ошибка',
                change_password: 'Изменить пароль',
                save_changes: 'Сохранить изменения',
                error_change_password: 'Ссылка устарела или пароль уже был изменён.',
                profile: 'Профиль',
                exit: 'Выйти',
                error_empty_data: 'Не заполнено обязательное поле',
                error_pattern_data: 'Неправильный формат',
                error_empty_checkbox: 'Необходимо согласиться',
                error_password_mismatch: 'Пароли не совпадают',
                error_password_same: 'Старый и новый пароли не должны совпадать',
                waiting: 'Ожидание...',
                subscription: 'Подписаться на рассылку новостей',
                will_be_available: 'Повторная отправка доступна через',
                seconds: 'сек',
                resend_password: 'Повторная отправка пароля',
                email_confirmed: 'Спасибо, адрес E-mail успешно подтверждён!',
                email_not_confirmed: 'Для выполнения действия необходимо подтвердить адрес E-mail пройдя по ссылке из регистрационного письма',
                email_confirm_post: 'Выслать письмо повторно',
                to_main_page: 'На главную страницу',
                redirection_: 'Ожидание...',
                check_email: 'Подтверждаю правильность написания и существование E-mail адреса',
                adminzone_enter: 'Войти в админзону',
                contact_send_message: 'Обратная связь',
                sender_email: 'E-mail отправителя',
                sender_name: 'Имя отправителя',
                contact_text: 'Текст сообщения',
                contact: 'Отправить сообщение',
                enter_reg: 'Вход/Регистрация',
                captcha_code: 'Код с капчи',
                sender_mail: 'Сообщение отправлено',
                exit_all: 'Выйти на всех устройствах'
            }
        }
    }
}