if (typeof mHLogin.i18n === 'undefined') {
    mHLogin.i18n = {
        languages: uHLogin.languages,
        get: function (tag) {
            return typeof this.data.de[tag] !== 'undefined' ? this.data.de[tag] : tag;
        },
        data: {
            de: {
                data_send: 'Daten gesendet',
                data_not_send: 'Daten NICHT gesendet',
                password: 'Passwort',
                input_password: '&ge;6 Ziffern und lateinische Zeichen',
                password_repeat: 'Passwort-Wiederholung',
                submit: 'Senden',
                sign_in: 'Eintreten',
                enter: 'Eintritt',
                registration_title: 'Anmeldung',
                phone: 'Telefonnummer',
                name: 'Vorname',
                surname: 'Name',
                address: 'Adresse',
                promocode: 'Promo-Code',
                familar: 'Zur Kenntnis genommen',
                terms: 'Nutzungsrichtlinien',
                conditions: 'alle Bedingungen angenommen',
                privacy_policy: 'Datenschutzrichtlinien',
                generate_password: 'Passwort erzeugen',
                and: 'und',
                on_email: 'An E-Mail',
                send_password: 'Passwort-Wiederherstellung',
                forgot_password: 'Passwort vergessen?',
                show_password: 'Passwort einblenden',
                hide_password: 'Passwort einblenden',
                remember_login: 'Angemeldet bleiben',
                close: 'Schließen',
                mess_password: 'Passwort wird an E-Mail gesendet werden',
                new_password: 'Neues Passwort',
                old_password: 'Aktuelles Passwort',
                u_error: 'Fehler aufgetreten',
                change_password: 'Passwort ändern',
                save_changes: 'Änderungen speichern',
                error_change_password: 'Der Link ist nicht mehr aktuell, oder das Passwort wurde schon geändert.',
                profile: 'Profil',
                exit: 'Abmelden',
                error_empty_data: 'Pflichtfeld bleibt leer',
                error_pattern_data: 'Unrichtiges Format',
                error_empty_checkbox: 'Zustimmung ist erforderlich',
                error_password_mismatch: 'Passwörter stimmen nicht überein',
                error_password_same: 'Alte und neue Passwörter sind übereinzustimmen',
                waiting: 'Bitte warten…',
                subscription: 'Newsletter bestellen',
                will_be_available: 'Wiedersendung ist nach …',
                seconds: 'Sek.',
                resend_password: 'Passwort-Wiedersendung',
                email_confirmed: 'Vielen Dank, die E-Mail-Adresse ist erfolgreich bestätigt!',
                email_not_confirmed: 'Um diese Aktion zu verwirklichen, hat man die E-Mail-Adresse zu bestätigen. Dafür folgen Sie dem Link aus Anmeldungsnachricht',
                email_confirm_post: 'E-Mail nochmals senden',
                to_main_page: 'Auf die Startseite',
                redirection_: 'Bitte warten…',
                check_email: 'Hiermit bestätige ich die Richtigkeit der Schreibweise und die Anwesenheit der E-Mail-Adresse',
                adminzone_enter: 'In die Admin-Zone eintreten',
                contact_send_message: 'Feedback',
                sender_email: 'E-Mail-Adresse von Sender/in',
                sender_name: 'Name von Sender/in',
                contact_text: 'Nachrichttext',
                contact: 'Nachricht senden',
                enter_reg: 'Anmeldung',
                captcha_code: 'Code vom CAPTCHA',
                sender_mail: 'Nachricht gesendet',
                exit_all: 'Auf allen Geräten abmelden'
            }
        }
    }
}