if (typeof mHLogin.i18n === 'undefined') {
    mHLogin.i18n = {
        languages: uHLogin.languages,
        get: function (tag) {
            return typeof this.data.en[tag] !== 'undefined' ? this.data.en[tag] : tag;
        },
        data: {
            en: {
                data_send: 'Data has been sent',
                data_not_send: 'Data NOT sent',
                password: 'Password',
                input_password: '&ge;6 numerals and Latin characters',
                password_repeat: 'Password repeat',
                submit: 'Submit',
                sign_in: 'Sign in',
                enter: 'Login',
                registration_title: 'Registration',
                phone: 'Phone number',
                name: 'Name',
                surname: 'Surname',
                address: 'Address',
                promocode: 'Promo code',
                familar: 'Familiar with',
                terms: 'Terms of Use',
                conditions: 'I accept all conditions',
                privacy_policy: 'Privacy Policy',
                generate_password : 'Generate password',
                and: 'and',
                on_email: 'To E-mail',
                send_password: 'Password recovery',
                forgot_password: 'Forgot your password?',
                show_password: 'Show password',
                hide_password: 'Hide password',
                remember_login: 'Remember me',
                close: 'Close',
                mess_password: 'The password will be sent to E-mail',
                new_password: 'New password',
                u_error: 'Runtime error',
                change_password: 'Change password',
                old_password: 'Current password',
                save_changes: 'Save changes',
                error_change_password: 'The link is out of date or the password has already been changed.',
                profile: 'Profile',
                exit: 'Exit',
                error_empty_data: 'Required field is not filled',
                error_pattern_data: 'Invalid format',
                error_empty_checkbox: 'You must agree',
                error_password_mismatch: 'Passwords don\'t match',
                error_password_same: 'Old and new passwords must not match',
                waiting: 'Waiting...',
                subscription: 'Subscribe to the newsletter',
                will_be_available: 'Resubmit available through',
                seconds: 'sec',
                resend_password: 'Resend password',
                email_confirmed: 'Thank you, your email has been successfully confirmed!',
                email_not_confirmed: 'To complete the action you must confirm the E-mail address by following the link from the registration letter',
                email_confirm_post: 'Resend email',
                to_main_page: 'Home page',
                redirection_: 'Waiting for redirect...',
                check_email: 'I confirm the correct spelling and existence of the E-mail address',
                adminzone_enter: 'Enter the adminzone',
                contact_send_message: 'Feedback',
                sender_email: 'Sender E-mail',
                sender_name: 'Sender name',
                contact_text: 'Message text',
                contact: 'Send message',
                enter_reg: 'Sign In/Registration',
                captcha_code: 'Captcha code',
                sender_mail: 'Message sent',
                exit_all: 'Exit on all devices'
            }
        }
    }
}