if (typeof mHLogin.i18n === 'undefined') {
    mHLogin.i18n = {
        languages: uHLogin.languages,
        get: function (tag) {
            return typeof this.data[tag] !== 'undefined' ? this.data[tag] : tag;
        },
        data: {
            data_send: '数据已被发送',
            data_not_send: '数据未被发送',
            password: '密码',
            input_password: '&ge;6 个数字和拉丁字符',
            password_repeat: '密码重复',
            submit: '发送',
            sign_in: '登录',
            enter: '登录',
            registration_title: '注册',
            phone: '电话号码',
            name: '名字',
            surname: '姓氏',
            address: '地址',
            promocode: '优惠代码',
            familar: '我了解',
            terms: '操作规定',
            conditions: '我同意所有的条件',
            privacy_policy: '隐私政策',
            generate_password: '生成密码',
            and: '和',
            on_email: '到电子邮箱',
            send_password: '恢复密码',
            forgot_password: '忘记了密码?',
            show_password: '显示密码',
            hide_password: '隐藏密码',
            remember_login: '记住登录信息',
            close: '关闭',
            mess_password: '密码将发送到电子邮箱',
            new_password: '新密码',
            old_password: '当前密码',
            u_error: '发生误差',
            change_password: '修改密码',
            save_changes: '保存修改',
            error_change_password: '链接已过期或密码已被更改',
            profile: '账户',
            exit: '登出',
            error_empty_data: '必填字段未被填写',
            error_pattern_data: '错误的格式',
            error_empty_checkbox: '必须同意',
            error_password_mismatch: '密码不 匹配',
            error_password_same: '旧和新密码不能 匹配',
            waiting: '等待…',
            subscription: '订阅时事通讯',
            will_be_available: '60秒后可重新发送',
            seconds: '秒',
            resend_password: '重新发送密码',
            email_confirmed: '谢谢，电子邮箱被成功确认!',
            email_not_confirmed: '要执行该操作，需要点击链接确认电子邮箱',
            email_confirm_post: '重新发邮件',
            to_main_page: '返回首页',
            redirection_: '等待…',
            check_email: '我确认电子邮箱存在，并是正确的。',
            adminzone_enter: '登录内容管理系统',
            contact_send_message: '反馈',
            sender_email: '寄件人的电子邮箱',
            sender_name: '寄件人的名字',
            contact_text: '消息文本',
            contact: '发消息',
            enter_reg: '登录/注册',
            captcha_code: '验证码中的代码',
            sender_mail: '消息已发送',
            exit_all: '从所有设备注销'
        }
    }
}